apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: vyos-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      selector:
        matchExpressions:
          - key: io.cilium.gateway/owning-gateway
            operator: Exists
      service:
        addresses:
          - LoadBalancerIP
