apiVersion: v1
kind: Namespace
metadata:
  name: trino
---
apiVersion: v1
kind: Namespace
metadata:
  name: openmetadata
---
apiVersion: v1
kind: Namespace
metadata:
  name: superset
---
apiVersion: v1
kind: Namespace
metadata:
  name: lakekeeper
---
apiVersion: v1
kind: Namespace
metadata:
  name: openeverest
---
apiVersion: v1
kind: Namespace
metadata:
  name: security-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
